source "http://rubygems.org"

gem "rake"
gem "jeweler"
gem "test-unit"
gem "downlow", "~> 0.1.3"
gem "thor"
gem "fssm"
gem "yajl-ruby"
gem "version_sorter", "~> 1.1.0"
gem "leftright"
gem "shoulda", ">= 0"
gem "fakeweb", ">= 1.2.8"
gem "rack-test"
gem "mocha"
