# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jim}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = %q{2010-11-04}
  s.default_executable = %q{jim}
  s.description = %q{jim is your friendly javascript library manager. He downloads, stores, bundles, vendors and compresses.}
  s.email = %q{aaron@quirkey.com}
  s.executables = ["jim"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "HISTORY",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bin/jim",
     "jim.gemspec",
     "lib/jim.rb",
     "lib/jim/bundler.rb",
     "lib/jim/cli.rb",
     "lib/jim/index.rb",
     "lib/jim/installer.rb",
     "lib/jim/rack.rb",
     "lib/jim/templates/commands",
     "lib/jim/templates/jimfile",
     "lib/jim/version_parser.rb",
     "test/fixtures/infoincomments.js",
     "test/fixtures/jimfile",
     "test/fixtures/jquery-1.4.1.js",
     "test/fixtures/jquery.color.js",
     "test/fixtures/jquery.metadata-2.0.zip",
     "test/fixtures/localfile.js",
     "test/fixtures/mustache.js/mustache.js",
     "test/fixtures/mustache.js/package.json",
     "test/fixtures/noversion.js",
     "test/fixtures/sammy-0.5.0/HISTORY.md",
     "test/fixtures/sammy-0.5.0/LICENSE",
     "test/fixtures/sammy-0.5.0/README.md",
     "test/fixtures/sammy-0.5.0/Rakefile",
     "test/fixtures/sammy-0.5.0/examples/backend/README.md",
     "test/fixtures/sammy-0.5.0/examples/backend/Rakefile",
     "test/fixtures/sammy-0.5.0/examples/backend/app.rb",
     "test/fixtures/sammy-0.5.0/examples/backend/app.ru",
     "test/fixtures/sammy-0.5.0/examples/backend/public/javascripts/app.js",
     "test/fixtures/sammy-0.5.0/examples/backend/public/javascripts/jquery.cloudkit.js",
     "test/fixtures/sammy-0.5.0/examples/backend/public/javascripts/jquery.js",
     "test/fixtures/sammy-0.5.0/examples/backend/public/javascripts/sammy.js",
     "test/fixtures/sammy-0.5.0/examples/backend/public/templates/index.html.erb",
     "test/fixtures/sammy-0.5.0/examples/backend/public/templates/task.html.erb",
     "test/fixtures/sammy-0.5.0/examples/backend/public/templates/task_details.html.erb",
     "test/fixtures/sammy-0.5.0/examples/backend/views/app.sass",
     "test/fixtures/sammy-0.5.0/examples/backend/views/index.haml",
     "test/fixtures/sammy-0.5.0/examples/form_handling/files/form.html",
     "test/fixtures/sammy-0.5.0/examples/form_handling/index.html",
     "test/fixtures/sammy-0.5.0/examples/hello_world/index.html",
     "test/fixtures/sammy-0.5.0/examples/location_override/README.md",
     "test/fixtures/sammy-0.5.0/examples/location_override/data.html",
     "test/fixtures/sammy-0.5.0/examples/location_override/index.html",
     "test/fixtures/sammy-0.5.0/examples/location_override/test.html",
     "test/fixtures/sammy-0.5.0/lib/min/sammy-0.5.0.min.js",
     "test/fixtures/sammy-0.5.0/lib/min/sammy-lastest.min.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.cache.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.haml.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.json.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.mustache.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.nested_params.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.storage.js",
     "test/fixtures/sammy-0.5.0/lib/plugins/sammy.template.js",
     "test/fixtures/sammy-0.5.0/lib/sammy.js",
     "test/fixtures/sammy-0.5.0/test/fixtures/partial",
     "test/fixtures/sammy-0.5.0/test/fixtures/partial.html",
     "test/fixtures/sammy-0.5.0/test/fixtures/partial.noengine",
     "test/fixtures/sammy-0.5.0/test/fixtures/partial.template",
     "test/fixtures/sammy-0.5.0/test/index.html",
     "test/fixtures/sammy-0.5.0/test/test_sammy_application.js",
     "test/fixtures/sammy-0.5.0/test/test_sammy_event_context.js",
     "test/fixtures/sammy-0.5.0/test/test_sammy_location_proxy.js",
     "test/fixtures/sammy-0.5.0/test/test_sammy_plugins.js",
     "test/fixtures/sammy-0.5.0/test/test_sammy_storage.js",
     "test/fixtures/sammy-0.5.0/test/test_server",
     "test/fixtures/sammy-0.5.0/vendor/jquery-1.4.1.js",
     "test/fixtures/sammy-0.5.0/vendor/jquery-1.4.1.min.js",
     "test/fixtures/sammy-0.5.0/vendor/jsdoc/doc.haml",
     "test/fixtures/sammy-0.5.0/vendor/jsdoc/jsdoc.rb",
     "test/fixtures/sammy-0.5.0/vendor/jslitmus.js",
     "test/fixtures/sammy-0.5.0/vendor/qunit-spec.js",
     "test/fixtures/sammy-0.5.0/vendor/qunit/qunit.css",
     "test/fixtures/sammy-0.5.0/vendor/qunit/qunit.js",
     "test/helper.rb",
     "test/test_jim_bundler.rb",
     "test/test_jim_cli.rb",
     "test/test_jim_index.rb",
     "test/test_jim_installer.rb",
     "test/test_jim_version_parser.rb"
  ]
  s.homepage = %q{http://github.com/quirkey/jim}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{jim is your friendly javascript library manager}
  s.test_files = [
    "test/fixtures/sammy-0.5.0/examples/backend/app.rb",
     "test/fixtures/sammy-0.5.0/vendor/jsdoc/jsdoc.rb",
     "test/helper.rb",
     "test/test_jim_bundler.rb",
     "test/test_jim_cli.rb",
     "test/test_jim_index.rb",
     "test/test_jim_installer.rb",
     "test/test_jim_version_parser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<downlow>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<version_sorter>, [">= 1.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<leftright>, [">= 0"])
    else
      s.add_dependency(%q<downlow>, [">= 0.1.3"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<version_sorter>, [">= 1.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<leftright>, [">= 0"])
    end
  else
    s.add_dependency(%q<downlow>, [">= 0.1.3"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<version_sorter>, [">= 1.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<leftright>, [">= 0"])
  end
end

